@url = http://localhost:8080
#
GET {{url}}/areas/
###
POST {{url}}/areas/
Content-Type: application/json

{
    "name": "Nombre del area de prueba"
}
###
GET {{url}}/areas/5f7f6f7992daeb00282ddf2d
###

PUT {{url}}/areas/5f7f6faf92daeb00282ddf2e
Content-Type: application/json

{
    "name": "Testing nueva area"
}

###
DELETE {{url}}/areas/5f7f6f7992daeb00282ddf2d